version: "3"
services:
  otel:
    image: grafana/otel-lgtm
    environment:
      # OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      # OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:4317
      OTEL_METRIC_EXPORT_INTERVAL: "5000"
    ports:
      - "3000:3000"
      - "4040:4040"
      - "4317:4317"
      - "4318:4318"
      - "9090:9090"
